export const sagaActions = {
  FETCH_SIDE_BAR_MENU: "FETCH_SIDE_BAR_MENU",
  FETCH_USER_DATA: "FETCH_USER_DATA",
  FETCH_LOGIN_DATA: "FETCH_LOGIN_DATA",
  POST_REGISTRATION_DATA: "POST_REGISTRATION_DATA",
  USER_LOGOUT: "USER_LOGOUT",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  GET_LOCATION: "GET_LOCATION",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  DASHBOARD_MENU_OPTIONS: "DASHBOARD_MENU_OPTIONS",
  SELECT_THEME: "SELECT_THEME"
};
