const Images = {
   
    Vehicle: require('../assets/images/vehicle.png'),
    Driver: require('../assets/images/driver-removebg-preview.png'),
    Department: require('../assets/images/department-removebg-preview.png'),
    Vehicletype: require('../assets/images/type.png'),
    status: require('../assets/images/status.png'),
    Speed: require('../assets/images/speed.png'),
    Fuel: require('../assets/images/fuelconsume.png'),
    Serial: require('../assets/images/serialno.png'),
    Mobile: require('../assets/images/Mobile.png'),
    Distance: require('../assets/images/Distance.png'),
    Running: require('../assets/images/Running.png'),
    Idle: require('../assets/images/Idle.png'),
    Starttime:  require('../assets/images/starttime.png'),
    Balance: require('../assets/images/Balance.png'),
    date: require('../assets/images/date.png'),
    Zone: require('../assets/images/zone.png'),
    Ignition: require('../assets/images/ignition.png'),
    km: require('../assets/images/kmm.png'),
    deviceid: require('../assets/images/deviceid.png'),
    stop : require('../assets/images/stop.png'),
    loginlogo : require('../assets/images/working-man.jpg'),
    Vehicle1: require('../assets/images/vehicle1.jpg'),
    Vehicle2: require('../assets/images/vehicle2.png'),
    Vehicle3: require('../assets/images/vehicle3.jpg'),
    tackingcar: require('../assets/images/gadi1.png'),



    
    DASHBOARD_CIRCLE: require('../assets/images/dashboardCenter.png'),
    SOS:require('../assets/images/SOS.png'),
    TRENDS:require('../assets/images/trendsLogo.png'),
    MODAL_IMAGE:require('../assets/images/vipul_goyal.jpeg'),
    TRANSLATE_lOGO:require('../assets/images/translateLogo.png'),
    TREND_LOGO:require('../assets/images/trends1.png'),

    DASHBOARD_IMAGE_VIEW1:require('../assets/dashboardImages/sports_1.jpeg'),
    DASHBOARD_IMAGE_VIEW2:require('../assets/dashboardImages/sports_2.jpeg'),
    DASHBOARD_IMAGE_VIEW3:require('../assets/dashboardImages/sports_3.jpeg'),
    DASHBOARD_IMAGE_VIEW4:require('../assets/dashboardImages/sports_4.jpeg'),
    DASHBOARD_IMAGE_VIEW5:require('../assets/dashboardImages/sports_5.jpeg'),
    DASHBOARD_IMAGE_VIEW6:require('../assets/dashboardImages/sports_6.jpeg'),
    DASHBOARD_IMAGE_VIEW7:require('../assets/dashboardImages/sports_7.jpeg'),
    DASHBOARD_IMAGE_VIEW8:require('../assets/dashboardImages/sports_8.jpeg'),
    DASHBOARD_IMAGE_VIEW9:require('../assets/dashboardImages/sports_9.jpeg'),
    DASHBOARD_IMAGE_VIEW10:require('../assets/dashboardImages/sports_10.jpeg'),

    NANARAO_PARK1:require('../assets/dashboardImages/nana-rao-park.jpg'),
    NANARAO_PARK2:require('../assets/dashboardImages/nana-rao-park_1.jpg'),
    NANARAO_PARK3:require('../assets/dashboardImages/nana-rao-fort_2.jpg'),

    DASHBOARD_IMAGE_VIEW11:require('../assets/dashboardImages/convention/convention_1.png'),
    DASHBOARD_IMAGE_VIEW12:require('../assets/dashboardImages/convention/convention_2.jpg'),
    DASHBOARD_IMAGE_VIEW13:require('../assets/dashboardImages/convention/convention_3.jpg'),
    DASHBOARD_IMAGE_VIEW14:require('../assets/dashboardImages/convention/convention_4.jpg'),
    DASHBOARD_IMAGE_VIEW15:require('../assets/dashboardImages/convention/convention_5.jpg'),
    DASHBOARD_IMAGE_VIEW16:require('../assets/dashboardImages/convention/convention_6.jpg'),
    DASHBOARD_IMAGE_VIEW17:require('../assets/dashboardImages/convention/convention_7.jpg'),
    DASHBOARD_IMAGE_VIEW18:require('../assets/dashboardImages/convention/convention_8.jpg'),
    DASHBOARD_IMAGE_VIEW19:require('../assets/dashboardImages/convention/convention_9.jpg'),
    DASHBOARD_IMAGE_VIEW20:require('../assets/dashboardImages/convention/convention_10.jpg'),
    DASHBOARD_IMAGE_VIEW21:require('../assets/dashboardImages/convention/convention_11.jpg'),
    DASHBOARD_IMAGE_VIEW22:require('../assets/dashboardImages/convention/convention_12.jpg'),
    DASHBOARD_IMAGE_VIEW23:require('../assets/dashboardImages/convention/convention_13.jpg'),
    DASHBOARD_IMAGE_VIEW24:require('../assets/dashboardImages/convention/convention_14.jpg'),
    DASHBOARD_IMAGE_VIEW25:require('../assets/dashboardImages/convention/convention_15.jpg'),
    DASHBOARD_IMAGE_VIEW26:require('../assets/dashboardImages/convention/convention_16.jpg'),
    
    GREENPARK_IMAGE_VIEW1:require('../assets/dashboardImages/green_park/green_park_1.jpg'),
    GREENPARK_IMAGE_VIEW2:require('../assets/dashboardImages/green_park/green_park_11.jpg'),
    GREENPARK_IMAGE_VIEW3:require('../assets/dashboardImages/green_park/green_park_3.jpg'),
    GREENPARK_IMAGE_VIEW4:require('../assets/dashboardImages/green_park/green_park_4.jpg'),
    GREENPARK_IMAGE_VIEW5:require('../assets/dashboardImages/green_park/green_park_5.jpg'),
    GREENPARK_IMAGE_VIEW6:require('../assets/dashboardImages/green_park/green_park_6.jpg'),
    GREENPARK_IMAGE_VIEW7:require('../assets/dashboardImages/green_park/green_park_7.jpg'),
    GREENPARK_IMAGE_VIEW8:require('../assets/dashboardImages/green_park/green_park_8.jpg'),
    GREENPARK_IMAGE_VIEW9:require('../assets/dashboardImages/green_park/green_park_9.jpg'),
    GREENPARK_IMAGE_VIEW10:require('../assets/dashboardImages/green_park/green_park_10.jpg'),
  
}

export default Images;